#! /usr/bin/env python

#voms-proxy-init -voms cms
#

#Higgs production cross sections: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHXSWG#Production_cross_sections_and_de
#mH = 125 GeV (check if it' better 125.09!)
    #ggH xsec: 48.58
    #VBF xsec: 3.782
    #WH xsec: 1.373
    #ZH xsec: 0.8839

sample = {
#### VBF
#private production test reason
    'VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-0_TuneCUETP8M1_13TeV-powheg-pythia8_PRIVATE-MC' : {
        'nevents' : 100000,
        'xsec'    : 1.,
        'matcheff': 1.,
        'kfactor' : 1.,
    },

# 2016 campaign
    'VBFH_HToSSTo4b_MH-125_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3' : {
        'nevents' : 1,
        'xsec'    : 1.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },


# 2017 campaign
    'VBFH_HToSSTo4b_MH-125_TuneCP5_13TeV-powheg-pythia8_RunIIFall17MiniAODv2' : {
        'nevents' : 1,
        'xsec'    : 1.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },


    # 2018 campaign
    'VBFH_HToSSTo4b_MH-125_TuneCP5_13TeV-powheg-pythia8_RunIIAutumn18MiniAOD' : {
        'nevents' : 1,
        'xsec'    : 1.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    

#### gg Fusion
#2016 campaign
    'ggH_HToSSTobbbb_MH-125_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3' : {
        'nevents' : 1,
        'xsec'    : 1.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

#2017 campaign
    'ggH_HToSSTobbbb_MH-125_TuneCP5_13TeV-powheg-pythia8_RunIIFall17MiniAODv2' : {
        'nevents' : 1,
        'xsec'    : 1.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

#2018 campaign
    'ggH_HToSSTobbbb_MH-125_TuneCP5_13TeV-powheg-pythia8_RunIIAutumn18MiniAOD' : {
        'nevents' : 1,
        'xsec'    : 1.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

## The following cross sections are taken from DAS/mcm!!!
    'QCD_HT50to100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 246300000.0,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 28060000.0,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 1710000.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 347500.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 32060.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 6829.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 1207.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 120.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 25.25,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 730.6,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_ext1-v3': {
        'nevents' : 1,
        'xsec'    : 38.06,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_ext1-v3': {
        'nevents' : 1,
        'xsec'    : 38.09,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1-v3': {
        'nevents' : 1,
        'xsec'    : 3.365,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1-v3': {
        'nevents' : 1,
        'xsec'    : 1., ##TODO: set to 0.0 in mcm!
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1-v3': {
        'nevents' : 1,
        'xsec'    : 1., ##TODO: set to 0.0 in mcm!
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'VBFHToBB_M-125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 3.861,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'WW_TuneCUETP8M1_13TeV-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 64.3,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'WZ_TuneCUETP8M1_13TeV-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 23.43,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'ZZ_TuneCUETP8M1_13TeV-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 10.16,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'DYJetsToQQ_HT180_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 1208.0,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext2-v2': {
        'nevents' : 1,
        'xsec'    : 4963.0,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 50260.0,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'WJetsToQQ_HT180_13TeV-madgraphMLM-pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 3105.,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'GluGluHToBB_M125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 30.52,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'ZH_HToBB_ZToQQ_M125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 0.5242,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'ZH_HToBB_ZToNuNu_M125_13TeV_powheg_pythia8_ext1-v3': {
        'nevents' : 1,
        'xsec'    : 0.1482,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'ZH_HToBB_ZToLL_M125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 0.07523,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'WminusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 0.3587,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'WplusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 0.5716,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'WminusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 0.1733,
        'matcheff': 1.,
        'kfactor' : 1.,
        },
    'WplusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 0.2791,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'ttHTobb_M125_13TeV_powheg_pythia8-v3': {
        'nevents' : 1,
        'xsec'    : 0.5401,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'bbHToBB_M-125_4FS_yb2_13TeV_amcatnlo-v3': {
        'nevents' : 1,
        'xsec'    : 0.3924,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph-v3': {
        'nevents' : 1,
        'xsec'    : 0.00162,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

    'GluGluToHHTo4B_node_SM_13TeV-madgraph-v3': {
        'nevents' : 1,
        'xsec'    : 0.009783,
        'matcheff': 1.,
        'kfactor' : 1.,
        },

   #ZJetsToNuNu
    #x-sec taken from DAS/mcm
    'ZJetsToNuNu_HT-100To200_13TeV-madgraph-v3' : {
        'nevents' : 1,
        'xsec'    : 93.35,
        'matcheff': 1.,
        'kfactor' : 1.,
    },
    'ZJetsToNuNu_HT-200To400_13TeV-madgraph-v3' : {
        'nevents' : 1,
        'xsec'    : 25.85,
        'matcheff': 1.,
        'kfactor' : 1.,
    },
    'ZJetsToNuNu_HT-400To600_13TeV-madgraph-v3' : {
        'nevents' : 1,
        'xsec'    : 3.584,
        'matcheff': 1.,
        'kfactor' : 1.,
    },
    'ZJetsToNuNu_HT-600To800_13TeV-madgraph-v3' : {
        'nevents' : 1,
        'xsec'    : 0.853,
        'matcheff': 1.,
        'kfactor' : 1.,
    },
    'ZJetsToNuNu_HT-800To1200_13TeV-madgraph-v3' : {
        'nevents' : 1,
        'xsec'    : 0.3934,
        'matcheff': 1.,
        'kfactor' : 1.,
    },
    'ZJetsToNuNu_HT-1200To2500_13TeV-madgraph-v3' : {
        'nevents' : 1,
        'xsec'    : 0.09543,
        'matcheff': 1.,
        'kfactor' : 1.,
    },
    'ZJetsToNuNu_HT-2500ToInf_13TeV-madgraph-v3' : {
        'nevents' : 1,
        'xsec'    : 0.002304,
        'matcheff': 1.,
        'kfactor' : 1.,
    },

    }


samples = {

    #DATA
    'data_obs' : {
        'order' : 0,
        'files' : ['METRun2016B-03Feb2017_ver2-v2'],
        'fillcolor' : 0,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Data",
        'weight': 1.,
        'plot': True,
        },


    ########################################################

    #QCD combined
    'QCD' : {
        'files' : [
            #'QCD_HT50to100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3',
            'QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3','QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3','QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3', 'QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3', 'QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3', 'QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3', 'QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3', 'QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3'],
        'fillcolor' : 920,
        'fillstyle' : 1001,
        'linecolor' : 920,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : 'QCD',
        'title' : 'QCD',
        'weight': 1.,
        'plot': True,
    },

    #TTbar
    'TTbar' : {
        'files' : ['TT_TuneCUETP8M2T4_13TeV-powheg-pythia8-v3',],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}",
        'weight': 1.,
        'plot': True,
    },


    #Single top
    'ST' : {
        'files' : ['ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_ext1-v3','ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_ext1-v3','ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1-v3','ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1-v3','ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1-v3'],
        'fillcolor' : 801,
        'fillstyle' : 1001,
        'linecolor' : 801,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Single t",
        'weight': 1.,
        'plot': True,
    },


    #Nice plotting
    'Top' : {
        'files' : ['TT_TuneCUETP8M2T4_13TeV-powheg-pythia8-v3','ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_ext1-v3','ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_ext1-v3','ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1-v3','ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1-v3','ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1-v3'],
        'fillcolor' : 798,
        'fillstyle' : 1001,
        'linecolor' : 798,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "t#bar{t}, single-t",
        'weight': 1.,
        'plot': True,
    },

    #ZJetsToNuNu
    'ZJetsToNuNu' : {
        'files' : ['ZJetsToNuNu_HT-100To200_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-200To400_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-400To600_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-600To800_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-800To1200_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-1200To2500_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-2500ToInf_13TeV-madgraph-v3'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z jets to NuNu",
        'weight': 1.,
        'plot': True,
    },


    'DYJetsToQQ' : {
        'files' : ['DYJetsToQQ_HT180_13TeV-madgraphMLM-pythia8-v3'],
        'fillcolor' : 858,
        'fillstyle' : 1001,
        'linecolor' : 858,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "DY jets to QQ",
        'weight': 1.,
        'plot': True,
    },
    'DYJetsToLL' : {
#        'files' : ['DYJetsToLL_Pt-50To100_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3','DYJetsToLL_Pt-100To250_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v2','DYJetsToLL_Pt-250To400_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3','DYJetsToLL_Pt-400To650_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3','DYJetsToLL_Pt-650ToInf_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3'],
        'files' : ['DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext2-v3'],
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "Z(ll) + jets",
        'weight': 1.,
        'plot': True,
},


    #Nice plotting
    'DYJets' : {
        'files' : ['ZJetsToNuNu_HT-100To200_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-200To400_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-400To600_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-600To800_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-800To1200_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-1200To2500_13TeV-madgraph-v3', 'ZJetsToNuNu_HT-2500ToInf_13TeV-madgraph-v3','DYJetsToQQ_HT180_13TeV-madgraphMLM-pythia8-v3', 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext2-v3'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "DY + jets",
        'weight': 1.,
        'plot': True,
    },


    #WJets
    'WJetsToLNu' : {
        'files' : ['WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W jets to LNu",
        'weight': 1.,
        'plot': True,
    },

    'WJetsToLNu_amcatnlo' : {
        'files' : ['WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W jets to LNu",
        'weight': 1.,
        'plot': True,
    },

    'WJetsToQQ' : {
        'files' : ['WJetsToQQ_HT180_13TeV-madgraphMLM-pythia8-v3'],
        'fillcolor' : 880,
        'fillstyle' : 1001,
        'linecolor' : 880,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W jets to QQ",
        'weight': 1.,
        'plot': True,
    },
    #Nice plotting
    'WJets' : {
        'files' : ['WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3','WJetsToQQ_HT180_13TeV-madgraphMLM-pythia8-v3'],
        'fillcolor' : 881,
        'fillstyle' : 1001,
        'linecolor' : 881,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W + jets",
        'weight': 1.,
        'plot': True,
    },


    #V+jets
    'Vjets' : {
        'files' : ['DYJetsToNuNu_PtZ-50To100_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3','DYJetsToNuNu_PtZ-100To250_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3','DYJetsToNuNu_PtZ-250To400_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3','DYJetsToNuNu_PtZ-400To650_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3','DYJetsToNuNu_PtZ-650ToInf_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v3','DYJetsToQQ_HT180_13TeV-madgraphMLM-pythia8-v3','DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext2-v3','WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v3','WJetsToQQ_HT180_13TeV-madgraphMLM-pythia8-v3'],
        'fillcolor' : 856,
        'fillstyle' : 1001,
        'linecolor' : 856,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "W/Z + jets",
        'weight': 1.,
        'plot': True,
    },

    #Dibosons
    'VV' : {
        'files' : ['WW_TuneCUETP8M1_13TeV-pythia8-v3','WZ_TuneCUETP8M1_13TeV-pythia8-v3','ZZ_TuneCUETP8M1_13TeV-pythia8-v3'],
        'fillcolor' : 602,
        'fillstyle' : 1001,
        'linecolor' : 602,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "WW, WZ, ZZ",
        'weight': 1.,
        'plot': True,
    },

    #VBF true higgs
    'VBF_Higgs' : {
        'files' : ['VBFHToBB_M-125_13TeV_powheg_pythia8-v3'],
        'mass' : 40,
        'ctau' : 0.005,
        'fillcolor' : 418,
        'fillstyle' : 1001,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "VBF H #rightarrow b#bar{b}",
        'weight': 1.,
        'plot': True,
    },

    'VH' : {
        'files' : ['ZH_HToBB_ZToQQ_M125_13TeV_powheg_pythia8-v3','ZH_HToBB_ZToNuNu_M125_13TeV_powheg_pythia8_ext1-v3','ZH_HToBB_ZToLL_M125_13TeV_powheg_pythia8-v3', 'WminusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8-v3','WplusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8-v3','WminusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8-v3','WplusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8-v3'],
        'fillcolor' : 420,
        'fillstyle' : 1001,
        'linecolor' : 420,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "VH",
        'weight': 1.,
        'plot': True,
    },

    'ggH' : {
        'files' : ['GluGluHToBB_M125_13TeV_powheg_pythia8-v3'],
        'fillcolor' : 635,
        'fillstyle' : 1001,
        'linecolor' : 635,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "ggH",
        'weight': 1.,
        'plot': True,
    },

    'ttH' : {
#        'files' : ['ttHTobb_M125_13TeV_powheg_pythia8','bbHToBB_M-125_4FS_yb2_13TeV_amcatnlo'],
        'files' : ['ttHTobb_M125_13TeV_powheg_pythia8-v3','bbHToBB_M-125_4FS_yb2_13TeV_amcatnlo-v3'],
        'fillcolor' : 821,
        'fillstyle' : 1001,
        'linecolor' : 821,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "ttH, bbH",
        'weight': 1.,
        'plot': True,
    },

    'HH' : {
        'files' : ['VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph-v3'],
        'fillcolor' : 825,
        'fillstyle' : 1001,
        'linecolor' : 825,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "VBF HH",
        'weight': 1.,
        'plot': True,
    },

    'SM_Higgs' : {
#        'files' : ['VBFHToBB_M-125_13TeV_powheg_pythia8-v3','ZH_HToBB_ZToQQ_M125_13TeV_powheg_pythia8-v3','ZH_HToBB_ZToNuNu_M125_13TeV_powheg_pythia8_ext1-v3','ZH_HToBB_ZToLL_M125_13TeV_powheg_pythia8-v3', 'WminusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8-v3','WplusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8-v3','WminusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8-v3','WplusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8-v3', 'GluGluHToBB_M125_13TeV_powheg_pythia8-v3', 'ttHTobb_M125_13TeV_powheg_pythia8-v3','VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph-v3',],#'bbHToBB_M-125_4FS_yb2_13TeV_amcatnlo-v3'],
        'files' : ['VBFHToBB_M-125_13TeV_powheg_pythia8-v3','ZH_HToBB_ZToLL_M125_13TeV_powheg_pythia8-v3', 'WminusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8-v3','WplusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8-v3', 'GluGluHToBB_M125_13TeV_powheg_pythia8-v3',],#'bbHToBB_M-125_4FS_yb2_13TeV_amcatnlo-v3'],
        'fillcolor' : 825,
        'fillstyle' : 1001,
        'linecolor' : 825,
        'linewidth' : 2,
        'linestyle' : 1,
        'label' : "SM Higgs",
        'weight': 1.,
        'plot': True,
    },






    ########################################################


    'ggH_MH-125_2016': {
        'files' : ['ggH_HToSSTobbbb_MH-125_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'fillcolor' : 801,
        'fillstyle' : 0,
        'linecolor' : 801,
        'linewidth' : 4,
        'linestyle' : 2,
        'label' : "ggH 2016 campaign",
        'weight': 1.,
        'plot': True,
        },


    ########################################################

    #VBF, m15
    'VBFH_M15_ctau0' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-0_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 15,
        'ctau' : 0.001,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 0 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau0p05' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-0p05_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 15,
        'ctau' : 0.05,
        'fillcolor' : 417,
        'fillstyle' : 0,
        'linecolor' : 417,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 0.05 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau0p1' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-0p1_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 15,
        'ctau' : 0.1,
        'fillcolor' : 802,
        'fillstyle' : 0,
        'linecolor' : 802,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 0.1 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau1' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-1_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m15 c #tau 1',
        'mass' : 15,
        'ctau' : 1,
        'fillcolor' : 602,
        'fillstyle' : 0,
        'linecolor' : 602,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 1 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau5' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-5_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 15,
        'ctau' : 5,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 5 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau10' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-10_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m15 c #tau 10',
        'mass' : 15,
        'ctau' : 10,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 10 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau25' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-25_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 15,
        'ctau' : 25,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 25 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau50' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-50_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m15 c #tau 50',
        'mass' : 15,
        'ctau' : 50,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 50 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau100' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-100_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'mass' : 15,
        'ctau' : 100,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 100 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau500' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-500_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'
            ],
        'mass' : 15,
        'ctau' : 500,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 500 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau1000' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-1000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
                ],
        'title' : 'VBFH m15 c #tau 1000',
        'mass' : 15,
        'ctau' : 1000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 1000 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau2000' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-2000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'mass' : 15,
        'ctau' : 2000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 2000 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau5000' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-5000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'
            ],
        'mass' : 15,
        'ctau' : 5000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 5000 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M15_ctau10000' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-15_ctauS-10000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'title' : 'VBFH m15 c #tau 10000',
        'mass' : 15,
        'ctau' : 10000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 15 GeV, c#tau_{0} = 10000 mm",
        'weight': 1.,
        'plot': True,
    },


#VBF, m40
    'VBFH_M40_ctau0' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-0_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m40 c #tau 0',
        'mass' : 40,
        'ctau' : 0.001,
        'fillcolor' : 632,
        'fillstyle' : 0,
        'linecolor' : 632,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = 0 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau0p05' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-0p05_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m40 c #tau 0.05',
        'mass' : 40,
        'ctau' : 0.05,
        'fillcolor' : 635,
        'fillstyle' : 0,
        'linecolor' : 635,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = 0.05 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau0p1' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-0p1_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m40 c #tau 0.1',
        'mass' : 40,
        'ctau' : 0.1,
        'fillcolor' : 600,
        'fillstyle' : 0,
        'linecolor' : 600,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = 0.1 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau1' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-1_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m40 c #tau 1',
        'mass' : 40,
        'ctau' : 1,
        'fillcolor' : 433,
        'fillstyle' : 0,
        'linecolor' : 433,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = 1 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau5' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-5_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m40 c #tau 5',
        'mass' : 40,
        'ctau' : 5,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau10' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-10_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m40 c #tau 10',
        'mass' : 40,
        'ctau' : 10,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau25' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-25_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m40 c #tau 25',
        'mass' : 40,
        'ctau' : 25,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau50' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-50_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m40 c #tau 50',
        'mass' : 40,
        'ctau' : 50,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau100' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-100_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'title' : 'VBFH m40 c #tau 100',
        'mass' : 40,
        'ctau' : 100,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau500' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-500_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'title' : 'VBFH m40 c #tau 500',
        'mass' : 40,
        'ctau' : 500,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = 500 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau1000' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-1000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'title' : 'VBFH m40 c #tau 1000',
        'mass' : 40,
        'ctau' : 1000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = 1000 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau2000' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-2000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'title' : 'VBFH m40 c #tau 2000',
        'mass' : 40,
        'ctau' : 2000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau5000' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-5000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'title' : 'VBFH m40 c #tau 5000',
        'mass' : 40,
        'ctau' : 5000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M40_ctau10000' : {
        'files' : [
            'VBFH_HToSSTobbbb_MH-125_MS-40_ctauS-10000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3',
            ],
        'title' : 'VBFH m40 c #tau 10000',
        'mass' : 40,
        'ctau' : 10000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 40 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    

    #VBF, m55
    'VBFH_M55_ctau0' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-0_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 0.001,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = 0 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau0p05' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-0p05_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 0.05,
        'fillcolor' : 824,
        'fillstyle' : 0,
        'linecolor' : 824,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = 0.05 mm",
        'weight': 1.,
        'plot': True,
    },
        'VBFH_M55_ctau0p1' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-0p1_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 0.1,
        'fillcolor' : 824,
        'fillstyle' : 0,
        'linecolor' : 824,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = 0.1 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau1' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-1_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m55 c #tau 1',
        'mass' : 55,
        'ctau' : 1,
        'fillcolor' : 813,
        'fillstyle' : 0,
        'linecolor' : 813,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = 1 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau1' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-1_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m55 c #tau 1',
        'mass' : 55,
        'ctau' : 1,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau5' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-5_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 5,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau10' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-10_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m55 c #tau 10',
        'mass' : 55,
        'ctau' : 10,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau25' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-25_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 25,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau50' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-50_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m55 c #tau 50',
        'mass' : 55,
        'ctau' : 50,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau100' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-100_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 100,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau500' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-500_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 500,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = 500 mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau1000' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-1000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m55 c #tau 1000',
        'mass' : 55,
        'ctau' : 1000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau2000' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-2000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 2000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau5000' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-5000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'mass' : 55,
        'ctau' : 5000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },
    'VBFH_M55_ctau10000' : {
        'files' : ['VBFH_HToSSTobbbb_MH-125_MS-55_ctauS-10000_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3'],
        'title' : 'VBFH m55 c #tau 10000',
        'mass' : 55,
        'ctau' : 10000,
        'fillcolor' : 826,
        'fillstyle' : 0,
        'linecolor' : 826,
        'linewidth' : 3,
        'linestyle' : 1,
        'label' : "m_{#pi} = 55 GeV, c#tau_{0} = ... mm",
        'weight': 1.,
        'plot': True,
    },



    }
